table dim_date
	lineageTag: d7a2ae8b-1c17-5959-9812-f09bbde65459
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		lineageTag: 968420d9-f977-51a7-9ff2-d87c901ac3c3
		summarizeBy: none
		sourceColumn: date_key

	column full_date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 58e71697-de98-5fcc-bf4c-ccd2e569e685
		summarizeBy: none
		sourceColumn: full_date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 8db3b8f0-7e79-5b49-8d48-46fad609b5e2
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: int64
		lineageTag: ce58766d-5e70-56dc-bd05-31e15b7497d4
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		isHidden
		lineageTag: ecd05ed1-f3b1-5c9e-9c3b-6b8b67173e7e
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		lineageTag: fb7468b7-fc38-59c2-9317-1a04c21ca1c3
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

	column year_month
		dataType: string
		lineageTag: b075714c-ccfe-5f8a-99d0-5acb6fc51d3a
		summarizeBy: none
		sourceColumn: year_month

	column day_of_week
		dataType: int64
		lineageTag: 912874f8-1f52-5721-90bb-4934112af9e2
		summarizeBy: none
		sourceColumn: day_of_week

	column is_weekend
		dataType: boolean
		lineageTag: 16cc4db1-c1c2-5ef3-b51d-290cc94b862d
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"date_key", Int64.Type}, {"full_date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_week", Int64.Type}, {"is_weekend", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

